spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LingChenBill/sell_config
          username: yourname
          password: yourpassword
          force-pull: true
          basedir: /Users/yourname/Documents/fork/springcloud/SpringCloud_Sell/config/basedir
          default-label: main
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'